// AES_Website/utils/testCases.ts
export const aesTestCases = [
    {
        key: "test1",
        label: "Test Case 1 (128-bit key, 1 block)",
        plaintextFile: "/test_files/aes-plaintext1.txt",
        keyFile: "/test_files/aes-key1.txt",
        ecbCiphertextFile: "/test_files/aes-ciphertext1-ecb.txt",
        cbcCiphertextFile: "/test_files/aes-ciphertext1-cbc.txt",
    },
    {
        key: "test2",
        label: "Test Case 2 (192-bit key, 2 blocks)",
        plaintextFile: "/test_files/aes-plaintext2.txt",
        keyFile: "/test_files/aes-key2.txt",
        ecbCiphertextFile: "/test_files/aes-ciphertext2-ecb.txt",
        cbcCiphertextFile: "/test_files/aes-ciphertext2-cbc.txt",
    },
    {
        key: "test3",
        label: "Test Case 3 (256-bit key, 3 blocks)",
        plaintextFile: "/test_files/aes-plaintext3.txt",
        keyFile: "/test_files/aes-key3.txt",
        ecbCiphertextFile: "/test_files/aes-ciphertext3-ecb.txt",
        cbcCiphertextFile: "/test_files/aes-ciphertext3-cbc.txt",
    },
    {
        key: "test4",
        label: "Test Case 4 (128-bit key, 4 blocks)",
        plaintextFile: "/test_files/aes-plaintext4.txt",
        keyFile: "/test_files/aes-key4.txt",
        ecbCiphertextFile: "/test_files/aes-ciphertext4-ecb.txt",
        cbcCiphertextFile: "/test_files/aes-ciphertext4-cbc.txt",
    },
    {
        key: "test5",
        label: "Test Case 5 (192-bit key, 5 blocks)",
        plaintextFile: "/test_files/aes-plaintext5.txt",
        keyFile: "/test_files/aes-key5.txt",
        ecbCiphertextFile: "/test_files/aes-ciphertext5-ecb.txt",
        cbcCiphertextFile: "/test_files/aes-ciphertext5-cbc.txt",
    },
    {
        key: "test6",
        label: "Test Case 6 (256-bit key, 6 blocks)",
        plaintextFile: "/test_files/aes-plaintext6.txt",
        keyFile: "/test_files/aes-key6.txt",
        ecbCiphertextFile: "/test_files/aes-ciphertext6-ecb.txt",
        cbcCiphertextFile: "/test_files/aes-ciphertext6-cbc.txt",
    },
    {
        key: "test7",
        label: "Test Case 7 (128-bit key, 7 blocks)",
        plaintextFile: "/test_files/aes-plaintext7.txt",
        keyFile: "/test_files/aes-key7.txt",
        ecbCiphertextFile: "/test_files/aes-ciphertext7-ecb.txt",
        cbcCiphertextFile: "/test_files/aes-ciphertext7-cbc.txt",
    },
    {
        key: "test8",
        label: "Test Case 8 (192-bit key, 8 blocks)",
        plaintextFile: "/test_files/aes-plaintext8.txt",
        keyFile: "/test_files/aes-key8.txt",
        ecbCiphertextFile: "/test_files/aes-ciphertext8-ecb.txt",
        cbcCiphertextFile: "/test_files/aes-ciphertext8-cbc.txt",
    },
    {
        key: "test9",
        label: "Test Case 9 (256-bit key, 9 blocks)",
        plaintextFile: "/test_files/aes-plaintext9.txt",
        keyFile: "/test_files/aes-key9.txt",
        ecbCiphertextFile: "/test_files/aes-ciphertext9-ecb.txt",
        cbcCiphertextFile: "/test_files/aes-ciphertext9-cbc.txt",
    },
]; 